# Generated by Django 3.2.5 on 2021-08-11 08:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='trade',
            field=models.ManyToManyField(blank=True, null=True, related_name='trade', to=settings.AUTH_USER_MODEL),
        ),
    ]
